services:
  adguardhome:
    image: adguard/adguardhome:${ADGUARD_VERSION:-v0.107.79}
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./adguardhome/workdir:/opt/adguardhome/work
      - ./adguardhome/confdir:/opt/adguardhome/conf
